### ISSUE TITLE
How do I get the public key from the signer?

### ISSUE THREAD

**Issue by ktrain10298765** [dev-natalie/RBXSigTools#1]
The only thing I see referencing to it is PublicKey.bin

**Comment by jerobsa** [comment]
Encode PublicKey.bin into Base64 and paste it into your client with a hex editor.

**Comment by ktrain10298765** [comment]
I don't know how.

**Comment by jerobsa** [comment]
Go to https://www.base64encode.org/ and scroll down until you find a place to upload files. Drag your PublicKey.bin file in there and click convert. Download the text file that it gives you. The contents of that text file is what you will be pasting into your client.

Open your client in a hex editor of your choice. Search for this string: `BgIAAACkAABSU0ExAAQAAAEAAQCjbUyx9OXTBcWEAonZOfAoT7YhMS+L21WwAZlsEjvzHXQpulpasNFhC1U6tBX6c8Qey2fiRBXHpqbh7vAC7u2niT6dMLLqY9UzII0jyxKD/EUODcQHTKpbM18FRobqLcvK0DNdIaHwypr7NRnSWk4NXhtM0v40W7/mr35PxbJ8rQ==`. Replace that string with the contents of the text file you downloaded.



https://user-images.githubusercontent.com/78948819/107837221-968ed680-6d65-11eb-93d4-2df508bc441b.mp4

**Comment by ktrain10298765** [comment]
Thanks for the help!
